# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-added-large-files
        exclude: '^models/.*\.pkl$'
    -   id: check-ast                         # Check files parse as valid Python
        exclude: ^(dags/).+(.py)$
    -   id: check-docstring-first             # Checks for a common error of placing code before the docstring.
    -   id: check-yaml                        # Attempts to load all yaml files to verify syntax.
        args: ['--unsafe']
    -   id: debug-statements                  # Check for debugger imports and py37+ breakpoint() calls in python source.
        exclude: ^(dags/).+(.py)$
    -   id: end-of-file-fixer                 # Makes sure files end in a newline and only a newline.
    -   id: mixed-line-ending                 # Replaces or checks mixed line ending. (Linux-only)
        args: ['--fix', 'lf']
    -   id: name-tests-test                   # Verifies that test files are named correctly.
        args: ['--pytest-test-first']
    -   id: no-commit-to-branch               # Protect specific branches from direct checkins.
        args: ['--branch', 'production']
    -   id: requirements-txt-fixer            # Sorts entries in requirements.txt and removes incorrect entries
    -   id: trailing-whitespace               # Trims trailing whitespace.
        args: [--markdown-linebreak-ext=md]
-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
        exclude: ^(dags/).+(.py)$
-   repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
    -   id: flake8
        args: [--ignore, 'E501,W503,E302,E402,E203']
        # 501: line length; W503: line break before bop; E302: expected line breaks,
        # E402: import order, E203: whitespace before ';'
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.detect.baseline', '--exclude-lines', '"(hash|id|image/\w+)":.*']
        exclude: .*/tests/*|.*/.secrets.toml
-   repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
-   repo: https://github.com/iterative/dvc
    rev: 3.59.1
    hooks:
    -   id: dvc-pre-commit
        language_version: python3
        stages:
        - pre-commit
